In [36]:
import numpy as np
import pandas as pd

In [ ]:
titanic = pd.read_csv("Titanic-Dataset.csv")

In [38]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [40]:
titanic.shape

(891, 12)

In [41]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [42]:
titanic[titanic['Age'].isnull()]['Age']

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
       ..
859   NaN
863   NaN
868   NaN
878   NaN
888   NaN
Name: Age, Length: 177, dtype: float64

In [44]:
titanic[titanic['Age'].isnull()]['Age'] = 0

/tmp/ipykernel_6564/889809466.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic[titanic['Age'].isnull()]['Age'] = 0

In [94]:
titanic.shape

(891, 12)

In [54]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,359.470258,0.325477,1.792368,23.799293,0.410774,0.345679,27.802338
std,293.017106,0.468816,1.166281,17.596074,0.856998,0.782915,49.348870
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,61.500000,0.000000,1.000000,6.000000,0.000000,0.000000,7.239600
50%,334.000000,0.000000,2.000000,24.000000,0.000000,0.000000,11.241700
75%,622.500000,1.000000,3.000000,35.000000,1.000000,0.000000,27.900000
max,891.000000,1.000000,3.000000,80.000000,5.000000,6.000000,512.329200

In [55]:
numdf = titanic[['PassengerId','Survived','Pclass','Age','SibSp','Parch','Fare']]

In [56]:
numdf.corr()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,0.233163,0.449905,0.433345,0.082602,0.125458,0.178816
Survived,0.233163,1.000000,0.047702,0.179501,0.066770,0.161488,0.338593
Pclass,0.449905,0.047702,1.000000,0.340352,0.224824,0.184519,-0.127304
Age,0.433345,0.179501,0.340352,1.000000,-0.060288,0.011886,0.257242
SibSp,0.082602,0.066770,0.224824,-0.060288,1.000000,0.416111,0.195946
Parch,0.125458,0.161488,0.184519,0.011886,0.416111,1.000000,0.253787
Fare,0.178816,0.338593,-0.127304,0.257242,0.195946,0.253787,1.000000

In [83]:
df1 = titanic[titanic['Pclass'] == 1][['Fare','Survived']]

In [84]:
df1.corr()

              Fare  Survived
Fare      1.000000  0.185072
Survived  0.185072  1.000000

In [79]:
df2 = titanic[titanic['Pclass'] == 2][['Fare','Survived']]
df2.corr()

              Fare  Survived
Fare      1.000000  0.056749
Survived  0.056749  1.000000

In [81]:
df3 = titanic[titanic['Pclass'] == 3][['Fare','Survived']]
df3.corr()

              Fare  Survived
Fare      1.000000  0.008783
Survived  0.008783  1.000000

In [ ]:
df = pd.read_csv('pima_indians_diabetes - pima_indians_diabetes.csv')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [47]:
s = df.set_index('Pregnancies')['Age']

In [48]:
s

Pregnancies
6     50
1     31
8     32
1     21
0     33
      ..
10    63
2     27
5     30
1     47
1     23
Name: Age, Length: 768, dtype: int64